@hostname=http://localhost
@port={{$dotenv PORT}}
@baseurl={{hostname}}:{{port}}
@auth=auth
@ac_token=

### Host
GET  {{baseurl}}
Authorization:Bearer {{ac_token}}

### Register
POST {{baseurl}}/{{auth}}/register
Content-Type:application/json

{
    "email":"test@gmail.com",
    "password":"123456"
}


### Login
POST {{baseurl}}/{{auth}}/login
Content-Type:application/json

{
    "email":"test@gmail.com",
    "password":"123456"
}


### Refresh Token
POST  {{baseurl}}/{{auth}}/refresh-token
Content-Type: application/json

{
    "refreshToken":""
}


### Logout
DELETE {{baseurl}}/{{auth}}/logout
Content-Type: application/json

{
    "refreshToken":""
}
