@hostname=http://localhost
@port={{$dotenv PORT}}
@baseurl={{hostname}}:{{port}}

GET  {{baseurl}}

### Login
POST {{baseurl}}/auth/login

### Register
POST {{baseurl}}/auth/register
Content-Type:application/json

{
    "email":"rvmdr1999@gmail.com",
    "password":"123ee4"
}

### Logout
DELETE {{baseurl}}/auth/logout

### Refresh Token
POST  {{baseurl}}/auth/refresh-token
